name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"

    - run: yarn --frozen-lockfile
    - run: yarn lint
    - run: yarn test:unit
    - run: yarn build
